# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-infer
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  java-infer:
    uses: fabriciofx/github-workflows/.github/workflows/java-infer-template.yml@main
